### ISSUE TITLE
Commenting on the Code

### ISSUE THREAD

**Issue by JoeNajowick** [CS305-Spring21/cs305-game#26]
While the project has become more familiar after spending time with it , I would like to request some additional inline comments  to the base code files to help further assist in navigation of the more complex elements of this project. This would also prove useful to see commenting style so I can try to make my end of the project more uniform.

**Comment by TheAlyxGreen** [comment]
Tons of comments and documentation added. While adding documentation for new code is an on-going, I'm going to close this issue for now.
